CREATE TABLE fiori_webapp (
                              oid uuid,
                              created_on timestamp NOT NULL,
                              modified_on timestamp NOT NULL,
                              created_by_user_oid uuid,
                              modified_by_user_oid uuid,
                              app_title varchar(100),
                              app_subTitle varchar(100),
                              app_shortTitle varchar(100),
                              app_info varchar(100),
                              app_description varchar(200),
                              name varchar(100) NOT NULL,
                              export_folder varchar(50) NOT NULL,
                              root_page_alias varchar(128) NOT NULL,
                              root_url varchar(50),
                              current_version varchar(10),
                              current_version_date timestamp,
                              ui5_min_version varchar(5) NOT NULL,
                              ui5_source varchar(100) NOT NULL,
                              ui5_theme varchar(50) NOT NULL,
                              ui5_app_control varchar(50) NOT NULL,
                              pwa_flag smallint NOT NULL,
                              pwa_background_color varchar(20),
                              pwa_theme_color varchar(20),
                              CONSTRAINT pk_fiori_webapp_oid PRIMARY KEY (oid)
);