<?php
namespace exface\UI5Facade\Facades\Elements;

use exface\Core\Widgets\SplitPanel;
use exface\Core\Widgets\Split;
use exface\Core\Widgets\Dialog;

/**
 * Renders a Split widget as sap.ui.layout.ResponsiveSplitter
 * 
 * For a simple split the structure is
 * 
 * ```
 * ResponsiveSplitter (generated by UI5Split) - has the id of the Split widget
 * |- PaneContainer (generated by UI5Split) - no id
 * |  |- SplitPane (generated by UI5SplitPanel) - no id
 * |  |- |- Panel (generated by UI5SplitPanel) - id of SplitPanel widget
 * |  |- SplitPane (generated by UI5SplitPanel) - no id
 * |  |- |- Panel (generated by UI5SplitPanel) - id of SplitPanel widget
 * 
 * ```
 * 
 * A nested split (e.g. dashboard) must be rendered as a single ResponsiveSplitter 
 * to make sure all panels collapse to a single slider. In this case the structure is
 * 
 * ```
 * ResponsiveSplitter (Split widget generated by UI5Split) - id of SplitWidget
 * |- PaneContainer (UI5 control generated by UI5Split) - no id
 * |  |- SplitPane (generated by UI5SplitPanel) - no id
 * |  |- |- Panel (SplitPanel widget generated by UI5SplitPanel) - id of SplitPanel
 * |  |- PaneContainer (generated by UI5Split of the nested Split) - no id (where is the id of the inner Split widget?)
 * |  |  |- SplitPane (generated by UI5SplitPanel in the nested Split) - no id
 * |  |  |- |- Panel (generated by UI5SplitPanel in the nested Split) - id of SplitPanel
 * |  |  |- SplitPane (generated by UI5SplitPanel in the nested Split)
 * |  |  |- |- Panel (generated by UI5SplitPanel in the nested Split)
 * 
 * ```
 * 
 * UI5Split and UI5Split both need different logic for regular contents and nested
 * splits!
 * 
 * @method \exface\Core\Widgets\Split getWidget()
 * @author Andrej Kabachnik
 *
 */
class UI5Split extends UI5Container
{
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\UI5Facade\Facades\Elements\UI5Container::buildJsConstructor()
     */
    public function buildJsConstructor($oControllerJs = 'oController') : string
    {
        $widget = $this->getWidget();
        // NOTE: buildJsPropertyLayoutData() is required for setting width/height
        // of nested splits! See UI5SplitPanel for details.
        $splitter = <<<JS

            new sap.ui.layout.PaneContainer({
                orientation: "{$this->getOrientation()}",
                panes: [
                    {$this->buildJsChildrenConstructors()}
                ],
                {$this->buildJsPropertyLayoutData()}
            })
            {$this->buildJsPseudoEventHandlers()}

JS;
        
        // If this widget is NOT a nested split, wrap the PaneContainer in a ResponsiveSplitter
        if (! $widget->hasParent() || ! ($widget->getParent() instanceof SplitPanel) && ! ($widget->getParent() instanceof Split)) {
            $height = $widget->getHeight()->isUndefined() ? '100%' : $this->buildCssHeight();
            $width = $widget->getWidth()->isUndefined() ? '100%' : $this->buildCssWidth();
            $splitter = <<<JS
        
    new sap.ui.layout.ResponsiveSplitter("{$this->getId()}", {
        height: "$height",
        width: "$width",
        rootPaneContainer: [
            $splitter
        ]
    })
    
JS;
        }
        
        // Add the page wrapper if needed
        if ($this->hasPageWrapper() === true) {
            return $this->buildJsPageWrapper($splitter);
        }
        
        return $splitter;
    }
        
    /**
     * 
     * @return string
     */
    protected function getOrientation()
    {
        return $this->getWidget()->isSideBySide() === true  ? 'Horizontal' : 'Vertical';
    }
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\UI5Facade\Facades\Elements\UI5AbstractElement::needsContainerHeight()
     */
    public function needsContainerHeight() : bool
    {
        return true;
    }
}